name: .NET Build/Test/Pack/Publish
author: Alex Vincent
description: Performs all the steps required to publish a versioned NuGet package to the official NuGet or GitHub packages feeds.

inputs:
  GITHUB_TOKEN:
    description: i.e. secrets.GITHUB_TOKEN
    required: true
  NUGET_API_KEY:
    description: i.e. secrets.NUGET_API_KEY
    required: false
  BuildConfiguration:
    description: i.e. Debug or Release
    default: Release
    required: false
  PublishPreview:
    description: Publish preview branch?
    required: false
  CodeCoverage:
    description: Default is 'true'
    default: "true"
    required: false

outputs:
  SemVer:
    description: i.e. 1.2.2
    value: ${{ steps.gitversion.outputs.SemVer }}
  FullSemVer:
    description: i.e. 1.2.2-2022-04-ci-updates.13
    value: ${{ steps.gitversion.outputs.FullSemVer }}
  BuildConfiguration:
    description: i.e. Debug or Release
    value: ${{ steps.setvars.outputs.BuildConfiguration }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: set vars
      shell: bash
      id: setvars
      run: |
        BuildConfiguration=${{ inputs.BuildConfiguration }}
        echo "BuildConfiguration=${BuildConfiguration:-"Release"}" >> $GITHUB_OUTPUT

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    # - name: gitversion install
    #   uses: gittools/actions/gitversion/setup@v0.9.7
    #   with:
    #     versionSpec: 5.x

    # #https://gitversion.net/docs/usage/
    # - name: gitversion determine version
    #   id: gitversionOLD
    #   uses: gittools/actions/gitversion/execute@v0.9.7
    #   with:
    #     useConfigFile: true

    - name: gitversion
      shell: pwsh
      id: gitversion
      run: |
        dotnet tool update -g GitVersion.Tool
        $GitVersion = dotnet-gitversion ${{ github.workspace }} /nofetch | ConvertFrom-Json
        Write-Host "SemVer=$($GitVersion.SemVer)"
        echo "SemVer=$($GitVersion.SemVer)" >> $env:GITHUB_OUTPUT
        Write-Host "FullSemVer=$($GitVersion.FullSemVer)"
        echo "FullSemVer=$($GitVersion.FullSemVer)" >> $env:GITHUB_OUTPUT

    - uses: f2calv/gha-check-release-exists@v1
      id: check-release-exists
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ReleaseName: ${{ steps.gitversion.outputs.SemVer }}

    - name: dotnet restore
      shell: bash
      run: dotnet restore --verbosity minimal --configfile nuget.config

    - name: dotnet build
      shell: bash
      run: dotnet build -c ${{ steps.setvars.outputs.BuildConfiguration }} --nologo --no-restore -p:Version='${{ steps.gitversion.outputs.SemVer }}' -p:SourceRevisionId=${{ github.sha }}

    - name: dotnet test
      shell: bash
      run: dotnet test -c ${{ steps.setvars.outputs.BuildConfiguration }} --nologo --no-restore --no-build -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=${{ github.workspace }}/coverage/

    - name: code coverage - coveralls (1 of 3) - .NET 6.x SDK
      if: github.event.inputs.CodeCoverage == 'true'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage/coverage.net6.0.info
        flag-name: run-net6.0
        parallel: true

    - name: code coverage - coveralls (2 of 3) - .NET 7.x SDK
      if: github.event.inputs.CodeCoverage == 'true'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage/coverage.net7.0.info
        flag-name: run-net7.0
        parallel: true

    - name: code coverage - coveralls (3 of 3)
      if: github.event.inputs.CodeCoverage == 'true'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        parallel-finished: true

    # - name: code coverage - report generator
    #   uses: danielpalme/ReportGenerator-GitHub-Action@4.5.8
    #   if: runner.OS == 'Linux'
    #   with:
    #     reports: ./coverage/coverage.*.info
    #     targetdir: ./coveragereport
    #     reporttypes: lcov
    #     tag: ${{ github.run_number }}_${{ github.run_id }}

    - name: reportgenerator
      shell: bash
      if: github.event.inputs.CodeCoverage == 'true'
      run: |
        dotnet tool update -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./coverage/coverage.*.info \
          -targetdir:./coveragereport \
          -reporttypes:lcov \
          -tag:${{ github.run_number }}_${{ github.run_id }}

    - name: code coverage - upload-artifact
      if: github.event.inputs.CodeCoverage == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: coveragereport
        path: coveragereport

    - name: dotnet pack
      shell: bash
      run: dotnet pack -c ${{ steps.setvars.outputs.BuildConfiguration }} --nologo --no-build --include-symbols -p:Version='${{ steps.gitversion.outputs.SemVer }}'
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    - name: dotnet push (api.nuget.org)
      shell: bash
      run: |
        if [[ "${{ inputs.NUGET_API_KEY }}" != "" ]]; \
        then
          dotnet nuget push ${{ github.workspace }}/src/**/*.nupkg --skip-duplicate -k ${{ inputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        else
          echo "::warning title=NUGET_API_KEY::NUGET_API_KEY is missing from secrets, skipping push to api.nuget.org."
        fi
      if: |
        steps.check-release-exists.outputs.ReleaseExists == 'false'
          && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event.inputs.PublishPreview == 'true')

    - name: dotnet push (nuget.pkg.github.com)
      shell: bash
      run: |
        dotnet tool update -g gpr
        gpr push ${{ github.workspace }}/src/**/*.nupkg -k ${{ inputs.GITHUB_TOKEN }}
      if: |
        steps.check-release-exists.outputs.ReleaseExists == 'false'
          && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event.inputs.PublishPreview == 'true')

    - name: create release ${{ steps.gitversion.outputs.FullSemVer }}
      uses: softprops/action-gh-release@v1
      if: |
        steps.check-release-exists.outputs.ReleaseExists == 'false'
          && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event.inputs.PublishPreview == 'true')
      with:
        tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
        name: ${{ steps.gitversion.outputs.FullSemVer }}
